### ISSUE TITLE
New SEM Page - Why Shred-it Missing CTA

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#312]
Why Shred-it section is missing the CTA Button. This applies to all new SEM pages that use this template. 

Example: https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding 

![image](https://github.com/user-attachments/assets/6be4e115-202c-4cf5-a447-6dae39988239)

**Comment by jindaliiita** [comment]
Fixed

**Comment by colinvlasak** [comment]
@jindaliiita looks to be fixed on most. Still appears to be missing on - https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-pricing

**Comment by jindaliiita** [comment]
@colinvlasak Can you do a hard refresh for this page. Because it's working fine for me.

**Comment by colinvlasak** [comment]
@jindaliiita must have been a caching issue. I see it now. Apologies for the back and forth on this.
