### ISSUE TITLE
Industry Pages - 2 Column Layout W/ Form

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#333]
Main content section should have form placeholder – this applies to all Who We Serve Pages
o	Example: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/accountants 

![image](https://github.com/user-attachments/assets/9eed09ec-486d-4400-b260-57637b8f5709)

**Comment by MarquiseRosier** [comment]
solved

**Comment by colinvlasak** [comment]
@MarquiseRosier the solution is causing a new issue. The two column layout should only apply to the top page section which contains the form. The entire is page is now split into a two column layout which is causing all of the rest of the content to be compressed. This needs to be fixed. All section below the first section with the form should span the full width of the page (within the standard margins)

EDS
![image](https://github.com/user-attachments/assets/7de6bd11-9195-49af-95ce-29217044c2c2)

Live Site

![image](https://github.com/user-attachments/assets/b0b297f1-cb9e-415d-8592-576c3164072b)

**Comment by jindaliiita** [comment]
@colinvlasak / @rwcsrichardspencer, whenever you encounter this issue on any page, simply add '**sidebar left**' to the section metadata **style** of that particular section.
<img width="791" alt="Screenshot 2024-10-21 at 11 19 48 AM" src="https://github.com/user-attachments/assets/92c7b817-c12f-462e-a690-5b6f6179f1f5">

**Comment by colinvlasak** [comment]
@jindaliiita I have updated the Who We Serve pages that were missing the sidebar page section metadata

The auto page isn't rendering quite right. The form is inline with the video vs. the text. Can you look into this and let me know how to fix?

https://main--shredit--stericycle.aem.live/en-us/who-we-serve/auto

![image](https://github.com/user-attachments/assets/7644105c-a8d4-4ce3-af95-a2001c286c02)

Will this be the same process for our service pages? if so how do we control what form is rendered in the sidebar? For the industry pages it's all the same form. For the service pages, the forms are different depending on the page?

**Comment by jindaliiita** [comment]
@rwcsrichardspencer On this page earlier video and text were in two different sections. Now, i have modified content to resolve this.
And from services pages which all pages you are referring ? Because currently form type is controlled by the code only.
Tagging @MarquiseRosier if he has more info.

**Comment by MarquiseRosier** [comment]
@colinvlasak thanks for pointing this out! @ravise5 @jalagari I believe this is an issue related to inserting specific forms on pages. We built the template purely to maintain the appropriate placement of elements. Please add this to your list of tickets; as this has to do with inserting the appropriate form

**Comment by jindaliiita** [comment]
Changed the assignee to @ravise5

**Comment by colinvlasak** [comment]
@jalagari @jindaliiita the form is now missing from the Industry pages. See below.

![image](https://github.com/user-attachments/assets/d2c91def-19e6-4e95-9c87-09c658623d87)

**Comment by ravise5** [comment]
@colinvlasak I just published the page can you recheck?

**Comment by colinvlasak** [comment]
@ravise5 once the pages are published it adds the form but the formatting issue is back

Examples: 
https://main--shredit--stericycle.aem.live/en-us/who-we-serve/hotels-and-hospitality
https://main--shredit--stericycle.aem.live/en-us/who-we-serve/finance
https://main--shredit--stericycle.aem.live/en-us/who-we-serve/real-estate
https://main--shredit--stericycle.aem.live/en-us/who-we-serve/education

![image](https://github.com/user-attachments/assets/f7ad16c1-9aba-48cf-9e49-dff8ebc4664e)

**Comment by ravise5** [comment]
@colinvlasak noted will address this.

**Comment by ravise5** [comment]
Closing this ticket as the issues discussed here are fixed
