### ISSUE TITLE
Mobile - Inconsistent Margins - Site Wide

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#496]
Across our mobile site the margins are inconsistent. Feels like there are at least 3 or 4 different margins that are randomly used. Can we ensure the margins are the same site wide?

I pasted a few examples below. This applies across the entire site though.

1. Inconsistent Mobile Margins Hero and Content Section

https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/paper-shredding-services

![image](https://github.com/user-attachments/assets/8695cce2-f32c-4404-8e5f-afddd81c389f)

https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/residential-shredding-services

![image](https://github.com/user-attachments/assets/57c9009d-9b9c-46c5-a845-f7d313a65e88)

https://main--shredit--stericycle.aem.live/en-us/who-we-serve/healthcare

![image](https://github.com/user-attachments/assets/48dc49e6-940c-45c3-8ae4-3531e0594326)

2. Blog Going Edge To Edge 

Example: https://main--shredit--stericycle.aem.live/en-us/blog/100-documents-to-take-to-communtiy-shredding-events (this is happening on all blog pages)

![image](https://github.com/user-attachments/assets/53502fc3-c4ab-4340-91ce-2350029304fb)

**Comment by colinvlasak** [comment]
@MarquiseRosier still seeing different margins widths on mobile pages

Example:

https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

![image](https://github.com/user-attachments/assets/a44e8a62-5873-480f-bd52-1faf242e7650)

https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/specialty-shredding-service

![image](https://github.com/user-attachments/assets/023dd9be-b932-4354-aabb-e90a5ae0eb85)

**Comment by MarquiseRosier** [comment]
Hey @colinvlasak just want to switch this over to @jalagari @ravise5. Guys; the Grid display you did on the forms.css here needs to respect the margins.

**Comment by MarquiseRosier** [comment]
@ravise5 @jalagari these lines in forms.css need to be adjusted to respect the margins for any page that uses those lines. 

https://github.com/aemsites/stericycle-shared/blob/c0a49e2e3c65b0238a635ed7341366acf55a9052/blocks/form/form.css#L892-L900

these are the effected pages:
https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/specialty-shredding-service

https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

**Comment by ravise5** [comment]
@MarquiseRosier its the padding of the `.default-content-wrapper` that is causing the uneven margins in mobile layout. Setting it to 0 in mobile layout should fix this. Your thoughts?

**Comment by MarquiseRosier** [comment]
Hey @ravise5 I have no ideas! But here to support if you need!

**Comment by colinvlasak** [comment]
@ravise5 @MarquiseRosier service pages look better. The blog issue is still not fixed - https://main--shredit--stericycle.aem.live/en-us/blog/100-documents-to-take-to-communtiy-shredding-events

Content is going edge to edge. It needs to respect the margins of the site.

![image](https://github.com/user-attachments/assets/3cea364c-50ad-4699-b022-48bac9154e5a)

**Comment by ravise5** [comment]
@MarquiseRosier I believe this is for you guys.

**Comment by colinvlasak** [comment]
@MarquiseRosier can we get this resolved soon?

**Comment by MarquiseRosier** [comment]
@colinvlasak @ravise5 did someone move this page from the directory? It's missing?
