### ISSUE TITLE
Mobile - One-Time Page - Nav Rendering Issues + 2 Column Layout

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#514]
On the one time page on mobile the hamburger nav is not displaying.

https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

![image](https://github.com/user-attachments/assets/7c7fc319-2600-4fcd-bc73-ddbf72d1af80)

You have to side scroll the page to see it and then it shows a white bar running down the side with no content

![image](https://github.com/user-attachments/assets/c04e4879-f964-447c-9162-cf468b49bfbc)

Additonallly. The main content section is not rendering properly. The form should stack not be a two column on mobile

![image](https://github.com/user-attachments/assets/4f5627a3-041a-40ac-9e05-2558e8ba44b2)

I am thinking the two may be related.

**Comment by ravise5** [comment]
This will be fixed via #508 
https://issue486--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

**Comment by ravise5** [comment]
This issue is now fixed

**Comment by colinvlasak** [comment]
@ravise5 still having this issue 

![image](https://github.com/user-attachments/assets/422feded-8e12-4a97-b11e-b3d3f57118a2)

**Comment by ravise5** [comment]
Is the cache cleared?
Seems to work at my side
![image](https://github.com/user-attachments/assets/258b8fcb-2d73-4d12-9bdc-95309fc5ef59)

**Comment by colinvlasak** [comment]
@ravise5 looks like it was mainly cache issues.

There is still one issue with the 2 column on smaller tablet layout. See below. It's not spanning the content the full width and adding a white bar up the side. 

![image](https://github.com/user-attachments/assets/5ee9f1cf-e3d0-4c05-84b0-e0e392c46e32)
