### ISSUE TITLE
Cards Issues - National Accounts

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#656]
Having some issues with the Cards component on the National Accounts pages. This is happening on multiple pages that use this block. Please fix for all. 

Example: https://main--shredit--stericycle.aem.page/en-us/national-accounts/amazon

1) When using bullets the component does not appear to recognize/respect spaces. In the doc there are spaces between the headings and bullets, and bullets and addtional text. On the webpage those spaces are not rendered.
2) The margin for the boxes doesn't align left to the page content

![image](https://github.com/user-attachments/assets/52df476a-3191-4b49-a957-f47d73eb0541)

Live Site: https://www.shredit.com/en-us/national-accounts/amazon

![image](https://github.com/user-attachments/assets/e342a5c8-9644-4d17-9d8b-190e64e85575)

**Comment by MarquiseRosier** [comment]
@colinvlasak I went ahead and just consolidated that bullet style; we might as well use checkmarks for everything as the bullet is one off aha the page should be fixed now!

**Comment by colinvlasak** [comment]
@MarquiseRosier this did not fix the spacing issue. We need to ensure there is space between the bullets and the heading below. There should be more space between the bullet and heading which are unrelated, then the heading and bullet which are related.

On page (incorrect):

![image](https://github.com/user-attachments/assets/a37b451c-e9b6-4940-9ff0-7e8969e2608d)


In document

![image](https://github.com/user-attachments/assets/655060a2-7327-4651-b8fe-5eadaa10470c)

**Comment by jindaliiita** [comment]
@colinvlasak Can you please check now? It's working fine on my end. The issue was with the authoring. We need to change the headings (e.g., Medium Tote) from normal to heading-6. If its fine then we can close this issue

**Comment by colinvlasak** [comment]
@jindaliiita looks much better. We can close this out.
